server:
    port: 8080

spring:
    dubbo:
        application:
            name: producer
        registry:
            address: zookeeper://127.0.0.1:2181
        protocol:
            name: dubbo
            port: 20880
        scan: com.teclan